python-babel/flask-babel

flask_babel/__init__.py
tests/tests.py

Adds `add_direction=True` option to `format_timedelta()` function (`|timedeltaformat` filter).  It’s useful for rendering relative times like “2 hours ago.”

Add add_direction=True option to format_timedelta

---

docs/index.rst
flaskext/babel.py
tests/tests.py

This is a change I have implemented three years ago (wow), but I realized I never submitted a pull request. Probably because my other pull request from 2012 was not merged, so I was a bit frustrated. :)
Anyway, I'm creating this pull request so that it's easier to find, if somebody wants to integrate it. This solves https://github.com/mitsuhiko/flask-babel/issues/2.

Support temporary language switch inside a request

---

flask_babel/__init__.py
tests/tests.py

This pull request updates the Flask-Babel testcase for datetime formatting with expected values that match the locale settings in Babel.
For example, leaving Flask-Babel out of things:
```python
>>> from babel.core import Locale
>>> l = Locale.parse('de_DE')
>>> l.datetime_formats.items()
[(u'medium', u'{1}, {0}'), (u'long', u"{1} 'um' {0}"), (u'full', u"{1} 'um' {0}"), (u'short', u'{1}, {0}')]
```
Flask-Babel's current testcase expects formats without the 'um' and ',' so this pull request adds them in.

Babel testcase updates

---

flask_babel/__init__.py
tests/tests.py

This patch subclasses `speaklater._LazyString` and adds an `__html__` method that Flask's default JSONEncoder will use to serialize a translated string.
Note:  This is an alternative implementation to https://github.com/python-babel/flask-babel/pull/81.

Enable speaklater._LazyString for Flask JSONEncoder by subclassing

---

flask_babel/speaklater.py

I work with lazy strings a lot and I have a task that uses them extensively and also produces some logging output containing them. In older versions of Flask Babel, I could simply throw a function's arguments into my logger and get a useful result. E.g. a list of tuples containing some lazy strings looked like this in the logfile:
[(l'0 to 49', 0, 0.0), ...]
The same list became this since the update:
[(<flask_babel.speaklater.LazyString object at 0x7f0d859e5a20>, 0, 0.0), ...]
Of course, I could wrap `str()` around every lazy string I want to log, but in case of a list, a simple `log(foo)` would become `log([str(elem) for elem in foo])`.
Adding a simple `__repr__` method (like the one of `_LazyString` of the old, standalaone speaklater) to the `LazyString` class makes life a lot easier …

Add __repr__ to LazyString

---

tox.ini

Run tests on Python 3.4 and Python 3.5 as well.

---

flask_babel/__init__.py
tests/tests.py

Support for threshold argument to format_timedelta function. Additionally, the version of Babel containing this function has already been released.

add threshold arg to format_timedelta function

---

MANIFEST.in

The current PyPI tarball doesn't have it.

Include README in source distributions

---

flask_babel/__init__.py
tests/tests.py

This fixes issue #117 by setting `babel_locale` in `force_locale` context manager instead of replacing locale getter. Babel extension instance is shared across threads (through `Flask.extensions`) which may cause wrong locale to be selected in request that is processed at the same time in one thread while another thread is using `force_locale`. Setting locale to request context is thread-safe as Flask doesn't share request contexts between threads. I've added a test case to verify that this fix works, and it failed without changes to `force_locale`.

Fix locale selection in multi-threaded Flask app when force_locale is used

---

flask_babel/__init__.py

pytz is available in standard Python 2.7 environment in GAE, see
https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27

Remove pytz.gae refecence

---

flask_babel/__init__.py
tests/test_integration.py

In Python 2 the `filter()` worked because it returned a list, but in Python 3 it's a generator which is never falsy.
Note that, while a bugfix, this could break applications where someone relied on this bug. However, I think it's very unlikely so probably safe for a bugfix release.

Fix check for presence of .mo file in translation directories

---

flask_babel/__init__.py
tests/test_date_formatting.py
tests/test_force_locale.py

Locale set by a `force_locale` context manager leaks between multiple threads when `force_locale` is used in application context rather than request context. This can be fixed by using `flask.globals._app_ctx_stack` as recommended by [Flask documentation on extension development](https://flask.palletsprojects.com/en/1.1.x/extensiondev/). Unlike `current_app`, the object on top of the `_app_ctx_stack` object is different in every application context so any attributes set to it do not change the same attributes in a different application context. This pull request is similar to #144, but it adds a test for the bug that the change fixes and moves tests related to `force_locale` to a new test module.

Fix force locale in app context and multiple threads

---

.github/workflows/test.yml
setup.py

Both are end-of-life:
- Python 3.5 as of 2020-09-30
- Python 3.6 as of 2021-12-23
Source: https://devguide.python.org/versions/#unsupported-versions

Drop support for Python 3.5 and 3.6

---

flask_babel/__init__.py

There is a small typo in flask_babel/__init__.py.
Should read `translations` rather than `tranlations`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, tranlations -> translations

---

flask_babel/__init__.py

This makes these callables (instead of `None` in both cases) available for use as functions in Jinja templates using Flask's/Jinja's own hook.
I took the liberty to turn the first two positional arguments into keyword arguments to align with the rest of the arguments and make it easier to understand what they refer to.
I also renamed the argument `x` to `s` (for "string") as used in the implementation of `Domain.gettext` to align it with the other anonymous functions' arguments' names.

Install `pgettext`, `npgettext` for Jinja templates

---

pyproject.toml
tests/test_date_formatting.py

Fix tests against babel 12.2.x

---

docs/index.rst

There is no `BABEL_DOMAINS`, it's just `BABEL_DOMAIN`. I introduced this back in  python-babel/flask-babel#194

Fix typo in config options example

---

flask_babel/__init__.py
tests/test_gettext.py

`list_translations()` was returning the default locale twice if there was a translation file for the default locale.

Fix list_translations() not to return default locale twice

---

pyproject.toml

Fix the `include` entries in `pyproject.toml` to include documentation files in sdist format only.  Otherwise, they are added to the top-level wheel directory and they end up being installed directly in the top-level site-packages directory, e.g.:
/usr/lib/python3.11/site-packages/CHANGELOG
/usr/lib/python3.11/site-packages/LICENSE
/usr/lib/python3.11/site-packages/README.md

Do not include documentation files in wheels

---

pyproject.toml

There is a typo in the description. This PR fixes it.
Best! :v:

Fix typo in description of pyproject.toml

---

flask_babel/__init__.py

resolves #229 
As discussed in #229, this replaces the deprecated `@locked_cached_property` with the `@cached_property`, since locking is not needed.

replace deprecated locked_cached_property decorator with cached_property
